import subprocess

header = 'm.jsxs("div",{className:"flex items-center justify-between p-5 border-b border-sidebar-border bg-sidebar/50",children:[m.jsxs("div",{className:"flex items-center gap-3",children:[m.jsx("div",{className:"p-2 rounded-lg bg-teal-500/10 text-teal-500",children:m.jsx(CwIcon,{className:"h-6 w-6"})}),m.jsxs("div",{children:[m.jsx("h2",{className:"text-lg font-bold text-foreground",children:"Configurações do Chatwoot"}),m.jsxs("p",{className:"text-xs text-muted-foreground",children:["Instância: ",m.jsx("span",{className:"font-semibold text-teal-400",children:r.instanceName})]})]})]}),m.jsxs("div",{className:"flex items-center gap-2",children:[m.jsxs(it,{type:"button",variant:"outline",size:"sm",onClick:()=>fetchConfig(!0),disabled:fetching||loading,className:"h-8 px-3 text-xs gap-1.5 text-teal-400 border-teal-500/30 hover:bg-teal-500/10",children:[m.jsx("svg",{className:`h-3.5 w-3.5 ${fetching?"animate-spin":""}`,fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:"2",children:m.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"})}),"Carregar Salvo"]}),m.jsx("button",{onClick:n,className:"rounded-lg p-1.5 text-muted-foreground hover:text-foreground hover:bg-sidebar-accent transition-colors",children:m.jsx(Es,{className:"h-5 w-5"})})]})]})'

footer = 'm.jsxs("div",{className:"flex items-center justify-between p-4 border-t border-sidebar-border bg-sidebar/50",children:[m.jsx(it,{type:"button",variant:"outline",onClick:handleDelete,disabled:loading,className:"text-xs text-red-500 border-red-500/30 hover:bg-red-500/10 hover:text-red-400",children:"Remover / Desativar"}),m.jsxs("div",{className:"flex items-center gap-2",children:[m.jsx(it,{type:"button",variant:"ghost",onClick:n,disabled:loading,className:"text-xs text-muted-foreground hover:text-foreground",children:"Cancelar"}),m.jsxs(it,{type:"button",onClick:handleSave,disabled:loading,className:"text-xs bg-teal-600 hover:bg-teal-500 text-white font-medium px-4 py-2 rounded-lg flex items-center gap-1.5 transition-colors",children:[loading&&m.jsx("svg",{className:"animate-spin h-3.5 w-3.5 text-white",fill:"none",viewBox:"0 0 24 24",children:[m.jsx("circle",{className:"opacity-25",cx:"12",cy:"12",r:"10",stroke:"currentColor",strokeWidth:"4"}),m.jsx("path",{className:"opacity-75",fill:"currentColor",d:"M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"})].filter(Boolean)}),"Salvar Configuração"]})]})]})'

with open('scratch/test_parts.js', 'w', encoding='utf-8') as f:
    f.write('var m, it, CwIcon, r, fetchConfig, fetching, loading, n, Es, handleDelete, handleSave;\nvar h = ' + header + ';\nvar ft = ' + footer + ';\n')

r = subprocess.run(['node', '-c', 'scratch/test_parts.js'], capture_output=True, text=True)
print('Header & footer test:', r.stderr.strip() or 'OK!')
